CREATE TABLE INVENTORY_CATEGORY(
	NAME VARCHAR(45) PRIMARY KEY,
	SUPERCATEGORY_NAME VARCHAR(45),
	FOREIGN KEY (SUPERCATEGORY_NAME) REFERENCES INVENTORY_CATEGORY (NAME)
	);

INSERT INTO INVENTORY_CATEGORY
	(NAME, SUPERCATEGORY_NAME) VALUES 
	('Vegetable', NULL),
	('Fruit', 'Vegetable');
	
ALTER TABLE INVENTORY_NAME ADD CATEGORY_NAME VARCHAR(45);
ALTER TABLE INVENTORY_NAME ADD FOREIGN KEY (CATEGORY_NAME) REFERENCES INVENTORY_CATEGORY (NAME);
;