CREATE TABLE INVENTORY_QUANTITY (
	ID VARCHAR(45) AUTO_INCREMENT PRIMARY KEY,
	QUANTITY INT,
	NAME VARCHAR(45),
	FOREIGN KEY (NAME) REFERENCES INVENTORY_NAME (NAME)
	);

INSERT INTO INVENTORY_QUANTITY
	(NAME, QUANTITY) VALUES 
	('Banana', 100),
	('Apple', 200)
;