CREATE domain IF NOT EXISTS jsonb AS other;

ALTER TABLE INVENTORY_NAME RENAME TO PRODUCT;

ALTER TABLE PRODUCT ADD CREATION DATE;
ALTER TABLE PRODUCT ADD ORIGIN VARCHAR(45);
ALTER TABLE PRODUCT ADD PRICE DOUBLE;
ALTER TABLE PRODUCT ADD CURRENCY VARCHAR(45);
ALTER TABLE PRODUCT ADD DETAILS JSONB;

ALTER TABLE INVENTORY_QUANTITY RENAME COLUMN NAME TO PRODUCT;
