ALTER TABLE INVENTORY_QUANTITY RENAME TO INSTRUCTION;

ALTER TABLE INSTRUCTION ADD DATE DATE;
ALTER TABLE INSTRUCTION ADD MATURITY DATE;
ALTER TABLE INSTRUCTION ADD TYPE VARCHAR(45);

UPDATE INSTRUCTION SET DATE='2020-01-01';
UPDATE INSTRUCTION SET MATURITY='2020-01-01';
UPDATE INSTRUCTION SET TYPE='given';